# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "py-triangle" %}
{% set version = "20250106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/drufat/triangle/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 79fd8d47da786aa97223140336662fd4ab8b387b742848e37163fc42c3ad182d
  - git_url: https://github.com/drufat/triangle-c
    git_rev: 8b9e1046e5cddab1298d3204f10c93665836cf99  # Keep that in sync with triangle python package 
    git_depth: 1
    folder: c


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  source_files:
    - tests/test_triangle.py
  imports:
    - triangle
  requires:
    - pip
    - pytest
    - numpy
  commands:
    - pip check
    - pytest tests/test_triangle.py

about:
  home: https://github.com/drufat/triangle
  summary: 'Python bindings to the triangle library'
  description: |
    Triangle generates exact Delaunay triangulations,
    constrained Delaunay triangulations, conforming Delaunay triangulations,
    Voronoi diagrams, and high-quality triangular meshes.
    The latter can be generated with no small or large angles, 
    and are thus suitable for finite element analysis.
  license: "LGPL and Triangle"
  license_file:
    - LICENSE
    - c/README

extra:
  recipe-maintainers:
    - Hofer-Julian
    - Huite
    - JoerivanEngelen
